version: 2
updates:
  - package-ecosystem: 'gomod'
    directories:
      - '/'
      - 'interceptor/'
    allow:
      - dependency-type: all
    schedule:
      interval: 'daily'
  - package-ecosystem: "docker"
    directory: "/"
    ignore:
      # Only update runners base image not builder
      - dependency-name: "registry.ci.openshift.org/openshift/release"
    schedule:
      interval: "weekly"
